name: motion_web
description: The web implementation for the Motion plugin.
version: 2.0.1
homepage: https://cendre.me
repository: https://github.com/mrcendre/motion
issue_tracker: https://github.com/mrcendre/motion/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

flutter:
  plugin:
    implements: motion
    platforms:
      web:
        pluginClass: WebMotion
        fileName: motion_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  motion_platform_interface: ^2.0.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
